name: flip_card_swiper
description: A customizable, swipeable card widget with smooth flip animations and haptic support.
version: 0.0.1+1
repository: https://github.com/LiquidatorCoder/flip_card_swiper
topics: [3d, card, swipe, transform, flip]

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: Flip cards swiper in action.
    path: screenshots/colored.gif

flutter:
